### PR TITLE
Use gattlib fork

### PR DESCRIPTION
**Pull request by danielunderwood**
Due to the issue mentioned in #173 and the fact that gattlib doesn't seem to be maintained anymore, I have forked the [BitBucket pygattlib repo](https://bitbucket.org/OscarAcena/pygattlib) to [danielunderwood/pygattlib](https://github.com/danielunderwod/pygattlib) to fix the boost dependencies and whatever else I come across. That fork is now uploaded on PyPI under [pygattlib](https://pypi.python.org/pypi/pygattlib).

This PR just swaps over the gattlib dependency to the version I've uploaded, which seems to be working on both python 2 and python 3 for me. You can see [this PR](https://github.com/danielunderwood/pygattlib/pull/1/files) to see the changes to gattlib to fix the boost includes.

### CODE REVIEW

**Comment by rgov** [comment]
Thanks, Daniel. What would you say to moving the pygattlib fork to under the pybluez organization (with you maintaining control over it)?

**Comment by danielunderwood** [comment]
Sounds like a good idea to me. I tried to transfer the repo, but it didn't seem to let me request a transfer without permissions to create a repo. Just let me know what I need to do to have it transferred. I don't know too much about how accounts on PyPI works, but I can look at transferring ownership of the package or adding maintainers if we want.

**Comment by danielunderwood** [comment]
I've transferred the repo over now. Just a head's up that I've updated the included version of bluez today, which seems to have broken some things.

**Comment by danielunderwood** [comment]
So the gattlib bluez updates are working now and I've added instalilng the ble dependencies to the travis config. Unfortunately, it's failing on python 3.6 on travis since travis is running Ubuntu 14.04, which doesn't have the version of libbboost-python needed for 3.6 in the repos. What do we want to do here? Here are a few options that I've considered:

* Just don't worry about making sure ble dependencies install correctly since the tests for pygattlib should hopefully handle that
* Use docker/vagrant to use a version of Ubuntu that does have the appropriate version (I've done this [in pygattlib](https://github.com/pybluez/pygattlib/commit/2038ddf9486ebb4a796ef27ce4dd346e07241aef))
* Build boost libs from source
* Install from other deb/repo (I can't seem to find debs/repos to use)

**Comment by rgov** [comment]
The docker variant doesn't work because Travis hasn't whitelisted bluez for install in a container.

I guess I'd prefer to just build boost. What's your preference?

**Comment by rgov** [comment]
Are these changes all still part of this pull request? Or can we split it up into less destabilizing changes?

**Comment by danielunderwood** [comment]
I apologize for all of those commits. The first couple are manually compiling and installing Boost.Python and the rest are trying to make the build work. It seems to work fine on py2, but can't find the python headers for py3. I'm not entirely sure what's going on with them.

**Comment by rgov** [comment]
Hi Daniel, what's the state of this branch?

**Comment by danielunderwood** [comment]
I apologize that I forgot about this PR. Priorities at work shifted and I forgot that it was open.

The main change for this branch, which was changing the dependency version of gattlib is there. Unfortunately, I haven't been able to get the automated tests working despite a couple different tries. I was hoping that Travis would migrate to Ubuntu 18.04 and that that would possibly fix the testing issue, but I haven't heard any news on that end.

There's also an issue with the pygattlib library that should also be fixed before this change gets merged in. I believe it came from a change in the bluez API, but I'll need to check on that when I get a chance.

**Comment by rgov** [comment]
No worries, but it would be great to get this finished off when you have time. Yes, it doesn't look like Travis supports 18.04 yet, nor even 16.04... maybe there is a way to get it to build on 14.04, after all?

**Comment by timdonovanuk** [comment]
I guess pybluez is not usable on a Pi Zero for BLE then? Gattlib is still an unresolved dependency and compiling it results in virtual memory exhaustion.

**Pull request closed without merging**
