### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by laksh225**
Change Python Supported Version Info for v0.22 and 0.23

### CODE REVIEW

**Comment by laksh225** [comment]
As mentioned in #320

**Review by rgov — DISMISSED** [review]

**Comment by rgov** [comment]
Thanks.

**Comment by laksh225** [comment]
:smiley:

**Comment by laksh225** [comment]
Should I do any changes? 
Asking because pull request hasn't been merged.

**Comment by rgov** [comment]
I think saying "Version 0.23" for Python 3 suggests that they should install a particular version. And I don't want to have to update this for every release. And I don't know if 0.23 was the first version to support Python 3, but we could say "Version 0.23 and newer."

The fix I'd really like to see for #320 though is actually resolving the bug, rather than documenting it. But the documentation is useful until it is resolved.

**Review by rgov — APPROVED** [review]

**Comment by rgov** [comment]
Thanks, I'll merge this in. Just to set future expectations, it's not likely I'll be able to review pull requests within 24 hours, so please give it some more time—maybe a week—before checking for updates. No one is actively working on this project, unfortunately.

**Comment by laksh225** [comment]
👍

**Pull request merged**
