### PR TITLE
Fix bug in Mac due to package_data not considering symlinks

### PR DESCRIPTION
**Pull request by thisiscam**
As titled.

### CODE REVIEW

**Comment by rgov** [comment]
Thanks for this contribution.

You write in a comment, 

> This doesn't quite actually work, need a way to preserve the symlinks

What is the ideal behavior you'd like to see?

**Comment by thisiscam** [comment]
> Thanks for this contribution.
> 
> You write in a comment,
> 
> > This doesn't quite actually work, need a way to preserve the symlinks
> 
> What is the ideal behavior you'd like to see?

My hypothesis was that some release of macOS changed its bundle structure to the following:
- LightAquaBlue.framework/
     - Resources (relative path symlink)
     - Versions/A/
         - Resources (actual resource location)
              - xxx.plist

Ideally, the package_data should respect that symlink and, instead of copying the resources directory twice (once for the actual location one for the symlink), it should forward the symlink to the bundle.

**Comment by rgov** [comment]
Hm, ok. I think that's the format that macOS bundles have always been, isn't it? There seems to be an underlying issue:  https://github.com/pypa/pip/issues/5919

**Comment by thisiscam** [comment]
I'm not really familiar with macOS bundles. I only assumed that this code was working before it was broken --- which could totally be the wrong assumption (i.e. the code was just ... broken). The currently master branch cannot load any of the resource/*.plist

**Comment by rgov** [comment]
This is a similar fix to #330, should evaluate both.

**Pull request closed without merging**
