### PR TITLE
a couple of improvements (needed to implement logical-link setup w/ SSP, entirely in Python)

### PR DESCRIPTION
**Pull request by MichalMaruska**
I'm ready to split to independent branches, and I might try to push the opcode_name/event_name functions to blueZ, if deemed appropriate.

### CODE REVIEW

**Comment by karulis** [comment]
Thank You for pull request.

Just couple of things:
- have You tried it with both python 2.x and 3.x?
- is there any chance that You could provide example code in python for that functionality?:)

Regarding pushing the opcode_name/event_name functions to blueZ
Well that would be good idea, but example script is probably more important now:)

Thanks again

**Comment by btashton** [comment]
Could we at least get the HCI_CHANNEL_USER in?   What example script would you like to see? I am happy to add it in.

**Comment by rgov** [comment]
@btashton I merged this but it broke the build. I'm not a Linux user, so I can't debug easily. Is this something you could look into? It's probably just missing the correct header.

**Comment by btashton** [comment]
@rgov I can take a look.  I had just cherry-picked 048f60b which was working.

**Comment by btashton** [comment]
@rgov see #193

**Pull request merged**
