### PR TITLE
msbt: Correct more partial LPSTR to LPWSTR migrations.

### LINKED ISSUE #307: OSError: An invalid argument was supplied when using bluetooth.find_service
## System

 - **Operating System: Windows 10 Home
 - **Hardware: PC internal Bluetooth (asus zenbook ux430ua)
 - **Python Version: 3.7.4
 - **PyBluez Version: 0.23

## Issue

I am trying to execute the sample code but the `bluetooth.find_service` method is throwing the error 
`OSError: An invalid argument was supplied.`

The code I am running is simply
```
import sys
import bluetooth
uuid = "b378db85-4ec3-4daa-828e-1b99607bd6a0"
addr = None

connection = bluetooth.find_service(uuid=uuid, address=addr)
```

The full error is 

```
Traceback (most recent call last):
  File ".\begin.py", line 10, in <module>
    connection = bluetooth.find_service(uuid=uuid, address=addr)
  File "C:\Users\charl\Anaconda3\lib\site-packages\bluetooth\msbt.py", line 243, in find_service
    dresults = bt.find_service (addr, uuidstr)
OSError: An invalid argument was supplied.
```

### PR DESCRIPTION
**Pull request by dogtopus**
Fixes #307.

~~This is not the end of it. We likely need to sweep through the whole _msbt.c codebase and move all LPSTR uses to LPWSTR in order to prevent issues like this from happening again.~~ I scanned through the code quickly and it seems that this is the last unconverted LPSTR usage. Let's hope that this is actually the last one.

### CODE REVIEW

**Review by Evineit — APPROVED** [review]
The error in #307 seems to be fixed, no problem building from this PR

> Python version: Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]

**Comment by dogtopus** [comment]
@rgov

**Comment by hiaselhans** [comment]
hi @dogtopus

can i use this pr in my fork?
https://github.com/airgproducts/pybluez2

**Comment by dogtopus** [comment]
> hi @dogtopus
> 
> can i use this pr in my fork?
> https://github.com/airgproducts/pybluez2

Sure. That's what forks are right?

**Pull request merged**
