### PR TITLE
Fix recv on OSX running python3

### LINKED ISSUE #217: pybluez RFCOMM recv broken on OSX + python3
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:** OSX 10.13, python 3.7
 - **Hardware:** (e.g., Raspberry Pi, external Bluetooth adaptor, etc.)
 - **PyBluez Version:** HEAD

## Issue
Invoking recv() results in a string being returned that's the binary data converted to ASCII.  For example, receiving 0x06 would result in the 6-digit string "b'\x06" (0x62 0x27 0x5c 0x78 0x30 0x36).

recv(1) thus always returns 0x62 regardless of what occurs on the wire.

### PR DESCRIPTION
**Pull request by vlovich**
Rather than doing complex things & ending up with a string just use
bytearray directly.  Also switch to a non-reentrant lock; usage of locking
is unclear since the code overall isn't thread-safe so having it in just
this one spot seems unnecessary.

Most importantly this gets rid of the call to x.tobytes() which results
in recv() returning a string containing the ASCII representation of data
instead of the data itself (at least on python3).  E.g. receiving byte
0x06 would result in the 6-digit string "b'\x06" being buffered so recv(1)
would actually return the ASCII for 'b' (0x62).

Fixes #217

### CODE REVIEW

**Comment by rgov** [comment]
FYI, consider using "macOS" (today's variant Apple likes) instead of "OSX" (which wasn't ever used).

You can also just open a pull request instead of filing an issue first, as long as the pull request describes the issue.

Which versions of Python did you test under?

```# multi-threaded usage isn't support (it's not currently).```

Should be "isn't supported".

**Comment by vlovich** [comment]
Done.  Tested on python3.7.  Will try to remember the ask going forward about PRs.

**Comment by rgov** [comment]
Thank you. Can you please test on the built-in macOS Python 2.7 before we merge this in?

**Comment by vlovich** [comment]
Works on 2.7 AFAICT.

**Comment by rgov** [comment]
Thank you!

**Pull request merged**
