### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by clach04**
Catch exception when no devices are detected.

Based on positive feedback for https://groups.google.com/forum/#!topic/pybluez/XgS2c2bOoOw.

### CODE REVIEW

**Comment by Bart274** [comment]
Can this be merged please? This fix works well and it's a shame that I have to change this manually if I need to install pybluez again for some reason

**Comment by karulis** [comment]
Fix is nice but I believe in this implementation we can silently pass some important OS errors
We probably should fix it layer lowe in C implementation

**Comment by clach04** [comment]
@karulis any objection to merging this and at a later date replacing with the C implementation you suggested?

**Comment by rgov** [comment]
@clach04 Thank you for the pull request. Is this still needed on Windows? Is there a specific OSError number that we should handle, or is it correct to catch all OSErrors?

**Comment by clach04** [comment]
@rgov  Yes still needed for Windows.

This PR is over a year old and I can't recall which number(s) I saw. My Python 3 installation is 3.6 and there are no pre-built binaries available so I can't easily check this now :-(

Interestingly under Python 2 I'm seeing a IOError, the .errno is None. The .message is 'No more data is available.'

**Comment by rgov** [comment]
@clach04 I merged this but we will need to sort out the OSError masking issue. Would you be able to build the module yourself on Windows and triage the problem? Where does that IOError originate?

**Pull request merged**
