### PR TITLE
Bluez cleanup

### PR DESCRIPTION
**Pull request by bbregeault**
These are some low hanging fruits found when looking at the bluez C code.
It's mostly style/formatting changes with a few macro replacements at the end.

### CODE REVIEW

**Comment by rgov** [comment]
Hi @bbregeault, thanks for your contribution.

I'd be happy to accept some code cleanup changes, but unfortunately modern version control systems don't make it very pleasant when you do things like bulk replace tabs with spaces, even when they end up making the code consistent. If the tools were better, I would totally run clang-format on the whole codebase and fix things up.

One of the main issues is that the "blame" information for virtually every line of code will be updated to show the whitespace commit, which will make it more tedious to figure out the history for a piece of code. Additionally, this will be almost guaranteed to make it very tedious to merge in any branches that were created before this change.

I'd be willing to accept everything but the tabs->spaces changes to btmodule.c, I think, but I can't see the complete diff on GitHub because it's too large.

**Comment by bbregeault** [comment]
Ok, I'll try to rework it.
Should I open a new pull request or change this one (I only know of git push -f to do this since the offending commit is the first one...) ?

**Comment by rgov** [comment]
Feel free to change this one, and sure you can force push to your branch.

**Comment by bbregeault** [comment]
In the light of your first comment, I put on top the commits I find most relevant (The first 3)
The rest is more about "aesthetics".
Feel free to tell me if some are useless from your point of view.

Rebasing with a bulk commit on top was indeed... time consuming... I'll remember this one, thanks !

**Comment by rgov** [comment]
Ok, I'll review the commits one by one.

- [x] 4b8189b Bluez module: Use PyDict_SetItemString where appropriate 
- [ ] fc0e0d4 Bluez module: Use Py_RETURN_NONE where appropriate [**issues remaining**]
- [x] dd01476 Bluez module: Use PyModule_AddIntMacro where appropriate  …
- [x] 69afd64 Bluez module: Fix some indentations
- [x] 6f8f3f7 Bluez module: End docstrings without newline + some fixes
- [x] bffbbbb  Bluez module: Various readability fixes
- [ ] 1af8570  Bluez module: Wrap lines more consistently around 80 chars  [**issues remaining**]

**Comment by bbregeault** [comment]
Again, since it is my first pull request, how should I fix the commits ?
Force push once more ? Won't that wreck the comments ?

Thanks for the guidance

**Comment by rgov** [comment]
I think you can just make a new commit and then push, that's fine. There's no one right answer, and it varies from pull request to pull request, or project to project. No big deal.

**Comment by bbregeault** [comment]
Here is the modified pull request.
I amended the last commit according to your 3rd comment and took out the last bits modifying the module initialization code.
Added a commit to address comment #2
I also added a new commit which refactors module initialization code. I didn't want to include it in this pull request at first but it addresses your last comment and adds a missing check while reducing the line count and (hopefully) improving readability.

**Comment by rgov** [comment]
I'm sorry I forgot about this pull request. I think it's a good idea to move forward with it. #244 will touch a bunch of docstrings so I'm not sure if we should rebase on this or not.

**Pull request merged**
