### PR TITLE
Use buffer interface for send, sendall and sendto methods in BlueZ binding

### LINKED ISSUE #287: Allow sending mutable bytes-like objects
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:** Linux, Windows ([widcomm-rfcomm](https://github.com/pybluez/pybluez/blob/30060cd07f625a24e4f47fe122f0acea54108dc8/widcomm/rfcommport.cpp#L264), [widcomm-l2cap](https://github.com/pybluez/pybluez/blob/30060cd07f625a24e4f47fe122f0acea54108dc8/widcomm/l2capconn.cpp#L275), [msbt](https://github.com/pybluez/pybluez/blob/30060cd07f625a24e4f47fe122f0acea54108dc8/msbt/_msbt.c#L272)) (could be more, further investigation needed)
 - **Hardware:** (e.g., Raspberry Pi, external Bluetooth adaptor, etc.) Any
 - **Python Version:** 3.8
 - **PyBluez Version:** master (30060cd)

## Issue

Trying to send a memoryview object using `BluetoothSocket.send()` API results in an exception which states that only read-only bytes-like objects are expected.

A quick look at the `bluez/btmodule.c` reveals that the method expects `s#` type args as the buffer. According to the python documentation `s#` only accepts read-only (non-mutable) str or bytes-like object i.e. practically only str and bytes. One way to resolve this is to switch to `s*` or `y*` so that the API also accepts mutable bytes-like objects (like memoryview).

### PR DESCRIPTION
**Pull request by dogtopus**
Partially fixes #287.

Tested and seems to work fine.

### CODE REVIEW

**Comment by rgov** [comment]
Thank you!

Could you describe how you tested and made sure this functionality was exercised?

There is no CI for Windows at this time, I'm trying to set it up with GitHub Actions but I'm not a Windows developer and struggle with installing the right SDK. If you have time to help with this, I'd appreciate it.

Here's my current [build.yml](https://github.com/rgov/pybluez/blob/master/.github/workflows/build.yml).

**Comment by dogtopus** [comment]
@rgov For now I just ran it with one of my own project that has a fair bit of RFCOMM traffic and also appears to pass a memoryview to the send() call (because asyncio). I wish I could test it with  `rfcomm_server.py` and a modified version of `rfcomm_client.py` but currently I have trouble starting up the `rfcomm_server.py` due to some unrelated issues.

**Comment by rgov** [comment]
@b1ack0wl Do you think you could test this one on your system as well?

**Comment by b1ack0wl** [comment]
> @b1ack0wl Do you think you could test this one on your system as well?

Ya! Would it be okay if I worked on this in a few hours? I'm currently busy at the moment, but will be free in a little bit. :)

**Comment by rgov** [comment]
@b1ack0wl Thanks! Absolutely no time pressure, this is all volunteer based. Just good to have a second pair of eyes on this change and I'm not running Linux.

**Comment by b1ack0wl** [comment]
Hey! Sorry for the long delay. I tested out the RFCOMM methods without any issue, but I only have one bluetooth device on my laptop (via PCI). I don't think having multiple adapters will cause an issue, but I wanted to at least say that in case an issue with having multiple adapters ever comes up.

**Review by rgov — APPROVED** [review]
Thank you, @dogtopus and @b1ack0wl. I'll merge this in.

**Pull request merged**
