### PR TITLE
Fix #224: Dll load error when importing on Windows 10...

### LINKED ISSUE #224: Dll load error when importing on newer version of Windows 10 due to missing dependency.
Irprops is missing on a newer version of Windows 10. Consider taking dependency on Bthprops instead.

## System

 - **Operating System:** Widnows 10 1809 (OS Build 18262.100)
 - **Hardware:** PC with external USB Bluetooth adapter.
 - **Python Version:** Python 3.7.1
 - **PyBluez Version:** 0.22

## Issue

In setup.py currently, _msbt.c depends on irprops:
```python
ext_modules.append(Extension('bluetooth._msbt',
                          include_dirs=["%s\\Include" % PSDK_PATH, ".\\port3"],
                          library_dirs=[lib_path],
                          libraries=["WS2_32", "Irprops"], # <-- here is the irprops reference
                          sources=['msbt\\_msbt.c']))
```

At least on the build of Windows 10 I'm running, irprops is not available (not in \Windows\System32).
This causes a DLL load error when trying to `import bluetooth._msbt as bt` in msbt.py:

Traceback (most recent call last):
  File "somefile.py", line 8, in <module>
    from bluetooth_interface import BluetoothInterface
  File "somefile.py", line 4, in <module>
    import bluetooth # pybluez
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pybluez-0.22-py3.7-win-amd64.egg\bluetooth\__init__.py", line 39, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pybluez-0.22-py3.7-win-amd64.egg\bluetooth\msbt.py", line 2, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pybluez-0.22-py3.7-win-amd64.egg\bluetooth\_msbt.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pybluez-0.22-py3.7-win-amd64.egg\bluetooth\_msbt.py", line 6, in __bootstrap__
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

It looks like irprops exposed bluetooth functionality at one point, but that functionality has been moved over to bthprops.
See MSDN documentation for one of the functions _msbt.c is referencing: [BluetoothFindFirstDevice](https://docs.microsoft.com/en-us/windows/desktop/api/bluetoothapis/nf-bluetoothapis-bluetoothfindfirstdevice)

I made this change locally and I am now able to install and import pybluez without error.
```python
ext_modules.append(Extension('bluetooth._msbt',
                          include_dirs=["%s\\Include" % PSDK_PATH, ".\\port3"],
                          library_dirs=[lib_path],
                          libraries=["WS2_32", "Bthprops"], # <-- changed irprops to bthprops
                          sources=['msbt\\_msbt.c']))
```

## Notes

I diagnosed the issue with [Dependencies](https://github.com/lucasg/Dependencies).
Examining the .pyd file for _msbt I saw that irprops was a missing dependency.
After looking up what functions irprops normally exposes, I found that bthprops also exposed those functions, was recommended by MSDN, and was available on my system.

I'm happy to submit a PR for the change, but I'm not sure how it might effect older versions of Windows or even when irprops was removed.

### PR DESCRIPTION
**Pull request by irvinec**
Added logic to setup.py:
1) Check to see if bthprops is present on the system.
2) If bthprops is present, we link to that instead of irprops.
3) If bthprops is not present, we fallback to linking to irprops.

Added get_windows_bluetooth_library_name helper function.

Tested on a recent version of Windows 10 with bthprops installed.
"py setup.py install"
Not tested on older versions of Windows.

### CODE REVIEW

**Comment by rgov** [comment]
Thanks @irvinec. I'm not a Windows user myself, so I cannot review this very intelligently.

One thing I wonder about is which version would we want to publish to PyPI? It looks like this makes it so there are two different packages that could be built.

**Comment by irvinec** [comment]
That is a really good point @rgov (and I'm dumb for not thinking of that). Building/Installing locally works, but that would not solve the issue for users who need to link against bthprops instead of irprops and install from PyPl.

From what I have briefly read, irprops is really only there for backwards compatibility for drivers built on the first bluetooth stack.
This makes me think we should favor linking to bthprops in new releases.
It also looks like bthprops is available going back to Windows XP (at least SP2).

With that in mind, my change is way overkill and not correct. I should have just changed irprops to bthprops :)
I'm still a bit concerned with breaking some users on Windows XP though. 
Maybe there is a way for me to get irprops on my version of Windows. Then the solution would be to just document the problem and solution somewhere in our documentation and not make a code change.

Thoughts?

From MSDN:
IrProps- A component that is used for backward compatibility for profile drivers that are created for the first version of the Bluetooth driver stack.

Note IrProps is provided only for backward compatibility. Use the BthProps component for new development.

**Comment by rgov** [comment]
Maybe we should collect additional opinions, but I'm not super upset about breaking compatibility with Windows XP. Those users can always install an older version of PyBluez. Windows XP is 17 years old and has been completely unsupported by Microsoft for 4 years. I don't think we need to support it forever.

**Comment by irvinec** [comment]
I agree and I can update my PR (probably tomorrow) to just link to bthprops and cut out all the other logic.
Plenty of workarounds for XP users, who should be in the minority, and we want to make sure we support users on new versions of Windows installing from PyPi.

**Comment by rgov** [comment]
Could you tell me a little bit more about how this change was tested?

**Comment by irvinec** [comment]
I didn't do extensive testing. I only verified on my own Windows 10 PC.

1) I verified both install from PyPi and setup.py install from source caused the error without this change (linking to irprops).
2) I made sure to completely clean and uninstall pybluez.
3) Made my change and rebuilt and reinstalled using py setup.py install.
4) Verified that everything was working in my own project that uses pybluez and no longer hit dll load error.

I realize that isn't much validation...

**Comment by rgov** [comment]
Could you please run `python setup.py bdist_egg` and attach the `.egg` file (it may end up in the `dist/` directory or something) to this pull request, and then we can ask others to test it out?

**Comment by irvinec** [comment]
I added the .egg file to a .zip and attached it.

[PyBluez-0.22-py3.7-win-amd64.egg.zip](https://github.com/pybluez/pybluez/files/2530047/PyBluez-0.22-py3.7-win-amd64.egg.zip)

**Comment by rgov** [comment]
Thanks. I think the .egg file already is a .zip :)

**Comment by rgov** [comment]
Please disregard the stalebot message. We do want this fix, once we can deliver a Windows 10 build.

**Comment by rgov** [comment]
Can anyone try installing the latest version (0.23) from PyPI and let us know if it works for you, so we can close out this ticket?

**Comment by Silpher8** [comment]
I created git just now for this, im having trouble installing pybluez. The error is always with irprops.lib
I tried pybluez 0.23 from pypi and the error persisted (also i noted there is no mention of the bthprops.lib in the source code of setup.py)
Edit: on windows 10

**Review by rgov — APPROVED** [review]

**Comment by rgov** [comment]
It seems like we need this change to make builds on Windows 10 pass. People targeting older Windows should install older PyBluez. If there are problems that I don't understand with this change, please propose another solution.

**Pull request merged**
