### PR TITLE
deprecate widcom and add linux wheels

### PR DESCRIPTION
**Pull request by hiaselhans**
I still have my [fork lying around](https://github.com/airgproducts/pybluez2) and would like merge it in piece by piece to close my repo.
This is a first step and it is deprecating the Widcom module plus adding linux wheels.
I think widcom is rarely used these days and as such is not worth maintaining.

### CODE REVIEW

**Comment by hiaselhans** [comment]
@rgov @dogtopus

**Comment by hiaselhans** [comment]
thanks stalebot to remind me of this PR!

@rgov @dogtopus what is the plan with this library?
All recent issues i see are related to installing on windows / mac.
I think we can definitely improve it, but it will require some work.
This PR is meant as a starter to merge my fork upstream, how can we move forward?

**Review by dogtopus — APPROVED** [review]

**Comment by dogtopus** [comment]
Sorry for the lack of response. I was busy with other stuff recently.

Anyway I checked your PR and it seems OK.

**Comment by AndreMiras** [comment]
Thanks for still merging stuff while being busy.
How about making a PyPI release since there're a bunch of interesting stuff in lately.
More specifically that fix https://github.com/pybluez/pybluez/pull/414
Without it the package cannot be installed from PyPI using pip on a recent setup

**Pull request merged**
